VoteWithYourWallet/Controllers/CausesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using VoteWithYourWallet.Models;

namespace VoteWithYourWallet.Controllers
{
    public class CausesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Causes
        public ActionResult Index()
        {
            
            var causes = db.Causes.Include(c => c.ApplicationUser);
            return View(causes.ToList());
        }

        // GET: Causes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cause cause = db.Causes.Find(id);
            if (cause == null)
            {
                return HttpNotFound();
            }


            // Check if user has signed cause before
            var userID = User.Identity.GetUserId();
            if (db.Signatures.Where(u => u.ApplicationUserID == userID && u.CauseID == id).Any())
            {
                ViewBag.AlreadySigned = "True";
            }
            else
            {
                ViewBag.AlreadySigned = "False";
            }




            return View(cause);
        }

        // GET: Causes/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: Causes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Cause cause, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                string path;
                string dbPath;
                if (file != null) {
                    //Generate random string code by User Mora, Source: https://stackoverflow.com/questions/17874086/generate-random-alphanumeric-string-into-password-field
                    var chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
                    var stringChars = new char[8];
                    var random = new Random();
                    
                    for (int i = 0; i < stringChars.Length; i++)
                    {
                        stringChars[i] = chars[random.Next(chars.Length)];
                    }

                    var finalString = new String(stringChars);
                    // Image upload amend code by Ankur Mistry https://www.c-sharpcorner.com/article/upload-files-in-Asp-Net-mvc/
                    path = Path.Combine(Server.MapPath("~/Content/Images"), finalString + Path.GetExtension(file.FileName));
                    dbPath = "~/Content/Images/" + finalString + Path.GetExtension(file.FileName);
                    file.SaveAs(path);
                    
                }
                else
                {
                    dbPath = "~/Content/Images/causePhoto.jpg";

                }
                
                db.Causes.Add(new Cause
                {

                    CauseID = cause.CauseID,
                    Title = cause.Title,
                    ApplicationUserID = cause.ApplicationUserID,
                    ShortDescription = cause.ShortDescription,
                    LongDescription = cause.LongDescription,
                    Target = cause.Target,
                    Image = dbPath
                });
                //db.Causes.Add(cause);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "FirstName", cause.ApplicationUserID);
            return View(cause);
        }

        // GET: Causes/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cause cause = db.Causes.Find(id);
            if (cause == null)
            {
                return HttpNotFound();
            }

            // Check if user has access rights
            var userID = User.Identity.GetUserId();
            if (db.Causes.Where(u => u.ApplicationUserID == userID).Any() || User.IsInRole("Admin"))
            {
                ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "FirstName", cause.ApplicationUserID);
                return View(cause);
            }
            
            return RedirectToAction("Index");
                
        }

        // POST: Causes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CauseID,ApplicationUserID,Title,ShortDescription,LongDescription,Image,Target")] Cause cause)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cause).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "FirstName", cause.ApplicationUserID);
            return View(cause);
        }

        // GET: Causes/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cause cause = db.Causes.Find(id);
            if (cause == null)
            {
                return HttpNotFound();
            }
            // Check if user has access rights
            var userID = User.Identity.GetUserId();
            if (db.Causes.Where(u => u.ApplicationUserID == userID).Any() || User.IsInRole("Admin"))
            {
                ViewBag.ApplicationUserID = new SelectList(db.Users, "Id", "FirstName", cause.ApplicationUserID);
                return View(cause);
            }

            return RedirectToAction("Index");
        }

        // POST: Causes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cause cause = db.Causes.Find(id);
            db.Causes.Remove(cause);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        // GET: Causes/Details/5
        public ActionResult Signees(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cause cause = db.Causes.Find(id);
            if (cause == null)
            {
                return HttpNotFound();
            }



            // Check if user has signed cause before
            var userID = User.Identity.GetUserId();
            if (db.Signatures.Where(u => u.ApplicationUserID == userID && u.CauseID == id).Any())
            {
                ViewBag.AlreadySigned = "True";
            }
            else
            {
                ViewBag.AlreadySigned = "False";
            }




            return View(cause);
        }


        // GET: Causes/_SignatureSmallList
        public ActionResult _SignatureSmallList()
        {
            return PartialView();
        }

        //// GET: Causes/_SignatureSmallListJson
        //public JsonResult _SignatureSmallListJson(int? id)
        //{
        //    var SignatureList = db.Signatures.Where(c => c.CauseID == id).OrderByDescending(s => s.DateTimeSigned).Take(5);


        //    return Json(SignatureList, JsonRequestBehavior.AllowGet);
        //}


        // GET: Causes/_SignCause
        public ActionResult _SignCause()
        {
            return PartialView();
        }

        // POST: Causes/_SignCause
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _SignCause([Bind(Include = "SignatureID,CauseID,ApplicationUserID,DateTimeSigned,Message")] Signature signature)
        {
            if (ModelState.IsValid)
            {
                db.Signatures.Add(signature);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return PartialView();
        }

        [HttpGet]
        public ActionResult _SignatureCount(string CauseID)
        {

            return PartialView();
        }


        static List<Signature> signatures = new List<Signature>();
        public ActionResult GetSignatures()
        {
            return View();
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

VoteWithYourWallet/Views/Causes/Create.cshtml
@model VoteWithYourWallet.Models.Cause
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Causes", FormMethod.Post,
new { @id = "createCause", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ApplicationUserID, new { Value = User.Identity.GetUserId() })

@*<div class="form-horizontal">*@
    <h4>Cause</h4>
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="form-group">
                <label for="Title" class="col-form-label">Name of your cause:</label>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @id = "causeName", @placeholder = "Enter the name of your cause..." } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label for="Title" class="col-form-label">Company or person your cause is targeted at:</label>
                @Html.EditorFor(model => model.Target, new { htmlAttributes = new { @class = "form-control", @id = "causeTarget", @placeholder = "Enter the persons or company your cause targets..." } })
                @Html.ValidationMessageFor(model => model.Target, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label for="ShortDescription" class="col-form-label">Brief summary of your cause:</label>
                @Html.TextAreaFor(model => model.ShortDescription, new { @class = "form-control", @id = "causeSummary", @placeholder = "Please briefly summarise your cause..." })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label for="LongDescription" class="col-form-label">Description of your cause:</label>
                @Html.TextAreaFor(model => model.LongDescription, new { @class = "form-control", @id = "causeDescription", @placeholder = "Cause description...", @rows = "3" })
                @Html.ValidationMessageFor(model => model.LongDescription, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label for="LongDescription" class="col-form-label">Upload an image (optional):</label>
                <input type="file" name="file" id="file" />
            </div>

                <div class="text-right">
                    <a class="btn btn-secondary" id="causeCancelButton" href="index.html">Cancel</a>
                    <input type="submit" class="btn btn-success" id="causeCreateButton" value="Create">
                </div>
            </div>
        </div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })




@*</div>*@
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VoteWithYourWallet/Views/Causes/Delete.cshtml
@model VoteWithYourWallet.Models.Cause

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cause</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LongDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LongDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VoteWithYourWallet/Views/Causes/Details.cshtml
@model VoteWithYourWallet.Models.Cause
@using Microsoft.AspNet.Identity;
@using VoteWithYourWallet.Models;
@using System.Web.Mvc;
@using System.Linq;

@{
    ViewBag.Title = "Cause Details";



}

<div class="row text-center">
    <div class="col-md-6 mx-auto"><h1 class="display-4">@Html.DisplayFor(model => model.Title)</h1></div>
</div>
<hr>
<div class="row">
    <div class="col-md-10 mx-auto">
        <div class="row">
            <div class="col-md-8">
                <div class="DetailsImgContainter" style="position:relative;">
                    @if (Model.Image.Length < 1)
                    {
                        <img class="img-fluid" src="images/causePhoto.jpg">
                    }
                    else
                    {
                        <img class="img-fluid" src="@Url.Content(Model.Image)">
                    }
                    <div class="TargetOverlay d-none d-sm-block">
                        <i class="fas fa-bullseye display-3"></i>
                        <strong class="display-4">@Html.DisplayFor(model => model.Target)&nbsp;</strong>
                    </div>
                </div>
                <div class="text-danger d-sm-none">
                    <i class="fas fa-bullseye display-5"></i>&nbsp;Veto target:&nbsp;
                    <strong class="display-5">@Html.DisplayFor(model => model.Target)</strong>
                </div>
                <div>
                    <p class="lead">@Html.DisplayFor(model => model.ShortDescription)</p>
                    <p>@Html.DisplayFor(model => model.LongDescription)</p>
                    <p class="text-right">
                        <small>Cause created by <strong>@Html.DisplayFor(modelItem => Model.ApplicationUser.FirstName) @Html.DisplayFor(modelItem => Model.ApplicationUser.LastName)</strong></small>
                    </p><br />
                    <span id="socialMediaButtons">
                        <!-- Social Media Buttons -->
                        <a href="https://www.facebook.com/sharer/sharer.php?u=@Request.Url.AbsoluteUri" class="social btn facebook" target="_blank"><i class="fab fa-facebook fa-lg"></i> Share</a>
                        <a href="https://twitter.com/home?status=@Request.Url.AbsoluteUri" class="social btn twitter" target="_blank"><i class="fab fa-twitter fa-lg"></i> Share</a>
                        <a href="https://plus.google.com/share?url=@Request.Url.AbsoluteUri" class="social btn google" target="_blank"><i class="fab fa-google fa-lg"></i> Share</a>
                        <a href="https://www.reddit.com/submit?url=@Request.Url.AbsoluteUri" class="social btn reddit" target="_blank"><i class="fab fa-reddit fa-lg"></i> Share</a>

                    </span>
                    <hr>
                    <p class="text-right">

                        <!-- Check if admin or creator -->
                        @if (User.IsInRole("Admin") || Model.ApplicationUserID == User.Identity.GetUserId())
                        {
                            <a href="@Url.Action("Edit", new { id = Model.CauseID })" class="btn btn-info">
                                <i class="fas fa-edit"></i> Edit
                            </a>
                            <a href="@Url.Action("Delete", new { id = Model.CauseID })" class="btn btn-danger">
                                <i class="fas fa-trash-alt"></i> Delete
                            </a>

                        }
                    </p>
                </div>
            </div>
            <div class="col-md-4">

                <p class="text-muted">This cause has...</p>
                <h1 class="display-4"><strong><span class="signatureCount">@Html.Partial("_SignatureCount", new ViewDataDictionary { { "CauseID", Model.CauseID } })</span> </strong><small class="text-muted">signatures</small></h1>
                <script>
                    // script for updating signature count
                    $(document).ready(function refreshText() {
                        $.ajax({
                            url: "/Signatures/GetSignatureCount/@Model.CauseID", success: function (result) {
                                result = JSON.parse(result);
                                $(".signatureCount").text(result);
                            }
                        });
                        setTimeout(refreshText, 1000);

                    });

                </script>
                @if (ViewBag.AlreadySigned == "True")
    {
            <button type="button" class="btn btn-danger btn-lg btn-block" id="signatureButton" disabled>Cause signed</button>
}
else
{
            <button type="button" class="btn btn-info btn-lg btn-block" id="signatureButton" data-toggle="modal" data-target="#signatureModal">Sign this cause</button>
}


                <br>
                <h5>Others who have signed..</h5>
                <table class="table table-sm" id="SignaturesList">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">
                                Name
                            </th>
                            <th scope="col">
                                When
                            </th>
                        </tr>
                    </thead>
                    <tbody id="LatestSignatures">
                        @Html.Partial("_SignatureSmallList", Model)
                    </tbody>
                </table>
                @Html.ActionLink("View all", "Signees", new { id = Model.CauseID })
            </div>
        </div>
    </div>
</div>
@*<script>
    $(document).ready(function refreshText() {
                        $.ajax({
                            url: "/Causes/_SignatureSmallList/@Model.CauseID", success: function (result) {
                                //result = JSON.parse(result);
                                //$("#LatestSignatures").text(result);

                            }
                        });
                        setTimeout(refreshText, 1000);

                    });

</script>*@


<p>
    @Html.ActionLink("Back to List", "Index")
</p>


<!-- Signature Modal-->
<div class="modal fade" id="signatureModal" role="dialog" aria-labelledby="signatureModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="signatureModalLabel">Sign a Cause</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @if (Request.IsAuthenticated)
                {
                    @Html.Partial("_SignCause", new ViewDataDictionary { { "CauseID", Model.CauseID } })
                }
                else
                {
                    <p>
                        You must be logged in to sign up to a cause.
                        <br />
                        Please <a href="#" data-dismiss="modal" data-toggle="modal" data-target="#loginModal" data-whatever="signIn" aria-controls="signIn">sign in</a> or
                        <a href="#" data-dismiss="modal" data-toggle="modal" data-target="#loginModal" data-whatever="signUp" aria-controls="signUp">register</a> an account with us.
                    </p>
                }
            </div>

        </div>
    </div>
</div>
<!-- /. Signature Modal -->

VoteWithYourWallet/Views/Causes/Edit.cshtml
@model VoteWithYourWallet.Models.Cause

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Cause</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CauseID)
    @Html.HiddenFor(model => model.ApplicationUserID)
    @Html.HiddenFor(model => model.Image)


    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LongDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LongDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LongDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VoteWithYourWallet/Views/Causes/Index.cshtml
@model IEnumerable<VoteWithYourWallet.Models.Cause>
@using Microsoft.AspNet.Identity.EntityFramework;
@using Microsoft.AspNet.Identity;
@using System.Web.Mvc;
@using System.Linq;
@using System.Net;
@using System.Web;
@using System.Web.Mvc;
@using VoteWithYourWallet.Models;
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="row text-center">
        <div class="col-md-6 mx-auto"><h1 class="display-4">Browse our causes</h1></div>
    </div>
    <hr>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>



    @{ var i = 1; }




    @foreach (var item in Model)
    {
        if ((i + 2) % 3 == 0)
        {
            @:<div class="row card-group align-content-center">
}






                  <div class="card">

                      @if (item.Image.Length < 1)
    {
                  <img class="card-img-top img-responsive" src="images/causePhoto.jpg">
}
else
{
                  <img class="card-img-top img-responsive" src="@Url.Content(item.Image)" alt="@Html.DisplayFor(modelItem => item.Title) image">
}
                      <div style=" z-index: 5; position:absolute; right:10px; top: 10px; text-align: right; vertical-align: middle; line-height: 25px;">
                          <a href="~/Causes/Signees/@item.CauseID" class="btn btn-info">
                              Signatures <span class="badge badge-light" id="SignatureCount_@item.CauseID">@Html.Partial("_SignatureCount", new ViewDataDictionary { { "CauseID", item.CauseID } })</span>
                          </a>
                      </div>
                      <script>
                    $(document).ready(function refreshText() {
                        $.ajax({
                            url: "/Signatures/GetSignatureCount/@item.CauseID", success: function (result) {
                                result = JSON.parse(result);
                                $("#SignatureCount_@item.CauseID").text(result);
                            }
                        });
                        setTimeout(refreshText, 1000);

                    });
                      </script>

                      <div class="card-body">
                          <h5 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h5>

                          <hr />
                          <p class="card-text">
                              @Html.DisplayFor(modelItem => item.ShortDescription)
                          </p>
                          <hr />
                          <p class="text-right text-danger">
                              <i class="fas fa-bullseye display-5"></i>
                              Campaign target: <strong>@Html.DisplayFor(modelItem => item.Target)</strong>
                          </p>
                      </div>







                      <div class="card-footer">
                          <p class="text-right">
                              <a href="@Url.Action("Details", new { id = item.CauseID })" class="btn btn-info">
                                  View details
                              </a>
                              @if (User.IsInRole("Admin") || item.ApplicationUserID == User.Identity.GetUserId())
            {
                  <a href="@Url.Action("Delete", new { id = item.CauseID })" class="btn btn-danger">
                      <i class="fas fa-trash-alt"></i>
                  </a>
}

                          </p>
                      </div>
                  </div>
            

            if (i % 3 == 0)
            {
                @:</div> <br />
        }
        if ((Model.Count() % 3 != 0) && i - 1 == Model.Count())
        {
            @:</div> <br />
    }
    i++;

    @*<tr>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShortDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LongDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Image)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CauseID }) |
                @Html.ActionLink("Details", "Details", new { id = item.CauseID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CauseID })
            </td>
        </tr>*@




}
    </div>

VoteWithYourWallet/Views/Causes/View.cshtml
@model IEnumerable<VoteWithYourWallet.Models.Cause>

@Html.DisplayForModel(Model)

@if (!Model.Any())
{
    <p>There are no causes matching your search terms.</p>
}

VoteWithYourWallet/Views/Causes/_SignCause.cshtml
@model VoteWithYourWallet.Models.Signature
@using Microsoft.AspNet.Identity;
@using VoteWithYourWallet.Models;


@{var db = new ApplicationDbContext();
    int CauseIDtoSign = Convert.ToInt32(ViewData["CauseID"]);
    string CauseTitle = (from Cause in db.Causes
                         where Cause.CauseID == CauseIDtoSign
                         select Cause.Title).FirstOrDefault();
    string CauseTarget = (from Cause in db.Causes
                          where Cause.CauseID == CauseIDtoSign
                          select Cause.Target).FirstOrDefault();
}

@using (Html.BeginForm("_SignCause", "Causes", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "SignCauseForm" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CauseID, new { Value = CauseIDtoSign })
    @Html.HiddenFor(model => model.ApplicationUserID, new { Value = User.Identity.GetUserId() })
    @Html.HiddenFor(model => model.DateTimeSigned, new { Value = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssK", System.Globalization.CultureInfo.InvariantCulture) })

    <p class="lead">By selecting the 'sign' button, you agree to sign the cause <strong>"@CauseTitle"</strong> and to vote with your wallet by not doing business with or purchasing from <strong>@CauseTarget</strong>.</p>

    <div class="form-group">
        @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "col-form-label" })
            @Html.TextAreaFor(model => model.Message, new { @class = "form-control", @placeholder = "Leave a public message about your support... (optional)"} )
            @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
    </div>

    <div class="modal-footer">
         <input type="button" class="btn btn-secondary" value="Close" data-dismiss="modal" />
            <input type="submit" value="Sign" class="btn btn-success" />
    </div>

}

VoteWithYourWallet/Views/Causes/_SignatureCount.cshtml
@using VoteWithYourWallet.Models

@{
    var CauseID = ViewData["CauseID"]?.ToString() ?? "";
    var lookupId = int.Parse(CauseID);
    var db = new ApplicationDbContext();

    int SignatureCount = (from row in db.Signatures
                          where row.CauseID == lookupId
                          select row).Count();

}
@SignatureCount

VoteWithYourWallet/Views/Causes/_SignatureSmallList.cshtml
@model VoteWithYourWallet.Models.Cause

@foreach (var item in Model.Signatures.OrderByDescending(s => s.DateTimeSigned).Take(5))
{

    <tr>
        <th scope="row"><i class="fas fa-user-circle"></i> @Html.DisplayFor(modelItem => item.ApplicationUser.FirstName) @Html.DisplayFor(modelItem => item.ApplicationUser.LastName)</th>
        <td><small><time class="timeago" datetime="@item.DateTimeSigned">@Html.DisplayFor(modelItem => item.DateTimeSigned)</time></small></td>
    </tr>
}